# Generated by Django 4.1.7 on 2023-03-11 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Conservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subfilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subfilo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('foto1', models.CharField(max_length=2000)),
                ('foto2', models.CharField(max_length=2000)),
                ('foto3', models.CharField(max_length=2000)),
                ('foto4', models.CharField(max_length=2000)),
                ('foto5', models.CharField(max_length=2000)),
                ('habitat', models.TextField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.clase')),
                ('conservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.conservacion')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.especie')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.estado')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.familia')),
                ('filo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.filo')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.genero')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.orden')),
                ('subfilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animales.subfilo')),
            ],
        ),
    ]
