# Generated by Django 4.1.7 on 2023-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_rename_clase_orden_orden_remove_animal_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfilo',
            name='subfilo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
