# Generated by Django 4.0 on 2023-03-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0005_remove_animal_subfilo_delete_subfilo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='nombre',
            new_name='nombreAnimal',
        ),
        migrations.RenameField(
            model_name='clase',
            old_name='nombre',
            new_name='nombreComun',
        ),
        migrations.RenameField(
            model_name='conservacion',
            old_name='nombre',
            new_name='nombreNivel',
        ),
    ]
